# Generated by Django 4.1 on 2023-11-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geolocation',
        ),
    ]
